# import User from './types/User.gql'
# import Token from './types/Token.gql'
# import AuthenticationData from './types/AuthenticationData.gql'

type RegistrationOutput {
  id: ID!
  email: String
  password: String
  refreshToken: String
  accessToken: String
}

type Query {
  getAllUsers: [User]
  getUser(id: ID!): User
  getToken(token: Token): AuthenticationData
}

type Mutation {
  registration(email: String!, password: String!): RegistrationOutput
  activate(activationCode: String): Boolean
}
