# import * from 'types.graphql'

input RegisterUser {
  email: String!
  password: String!
  fullName: String!
  nickname: String!
}

type Query {
  getAllUsers: [User]
  getUser(id: ID!): User
}

type Mutation {
  registration(input: RegisterUser): User
  activate(activationCode: String): Boolean
  login(login: String, password: String): User
  logout: Boolean 
}

